### ISSUE TITLE
Get array item in the format

### ISSUE THREAD

**Issue by alexzaytsev-newsroomly** [scottrippey/SmartFormat.NET#102]
Suppose i have a model like so:

```
 public class Model
        {
            public A A { get; set; }
        }

        public class A
        {
            public B B { get; set; }

            public List<B> Bs { get; set; }
        }

        public class B
        {
            public string Empathy { get; set; }
        }
```

Now if i try to access my format here 
```
var x = new Model { A = new A { B = new B{Empathy = "single" }, 
Bs = new List<B> { new B { Empathy = "list" } } } }; 
var val1 = Smart.Format("{A.B.Empathy}; {Bs[0].Empathy}", x);
var val2 = Smart.Format("{A.B.Empathy}; {Bs.First().Empathy}", x);
```

In both cases i only get the `"single; "` string.

Is it possible to get an array item from a model?

I get it working like so:
```
var list = new List<B> { new B { Empathy = "a" } };

var var3 = Smart.Format("{x[0].Empathy}", new { x = list });
```

In this case `var3` contains "a"; but i want to do it off lists on models, too.

here's a .net fiddle:  https://dotnetfiddle.net/q24Gf2

**Comment by axunonb** [comment]
Hi Alex
For testing it's better not to suppress exceptions. So witch them on:
```
Smart.Default.Settings.FormatErrorAction = ErrorAction.ThrowError;
Smart.Default.Settings.ParseErrorAction = ErrorAction.ThrowError;
```
Then you will see:
1. val1 throws a parse exception, because the array ```Bs``` in the selector cannot be evaluated. Why? It must read:
```var val1 = Smart.Format("{A.B.Empathy}; {A.Bs[0].Empathy}", x);```
// watch the missing **A.** in 2nd placeholder
```result: single; list```
2. val2 throws a parse exception, because ```First()``` is an **extension method**. You can only use parameterless methods built into a class **as members**.

**Comment by axunonb** [comment]
@alexzaytsev-newsroomly: Can the issue be closed with the answer given?

**Comment by alexzaytsev-newsroomly** [comment]
Sure, thanks for your help
