### ISSUE TITLE
Problem using Nuget Package in ".NET Fiddle"

### ISSUE THREAD

**Issue by willianfalbo** [scottrippey/SmartFormat.NET#104]
Hi guys,
I found a problem when we try to execute the code on ".NET Fiddler". Basically it's not working in Console Application online. Follow below the example:
https://dotnetfiddle.net/2yaKKZ

If we try to run the same code locally on VS17 (v4.5 framework), it works fine!

I got in touch with **.NET Fiddle Team**, just to check if the problem was there, but they found the problem is inside of SmartFormat.NET package. Please find below the e-mail details:

Kind Regards, Willian
-----------------------------------------------------------------------
Date: 05/May/2018
From: tickets@dotnetfiddle.uservoice.com
Contact Name: Jonathan Magnan

Hello Willian,

We have investigated the issue and found the problem. Unfortunately, I don't think we will do anything at this moment.

The issue is caused by the following line: https://github.com/scottrippey/SmartFormat.NET/blob/19e7f9c543730037b761f0123dd929e77196ab1d/src/SmartFormat/Extensions/ListFormatter.cs#L122

The method `CallContext.LogicalGetData(key);` is marked [SecurityCritical] and we do not provide yet access to some security that the method is requesting.

Honestly, we find it weird that the library needs to use this namespace. We didn't investigate all their codes but from what we have looked, they could avoid it.

You can also find a post about it here: https://github.com/scottrippey/SmartFormat.NET/issues/75#issuecomment-264638654

Perhaps you could contact them and ask them if they could remove code that references to it?

We might add some features later this year to give some additional trust to some known library such this one, but for now, there is no plan to support this library.

Let me know if our explanation is clear.

Best Regards,

Jonathan

**Comment by axunonb** [comment]
Thanks for the hint. Indeed this is a [known issue](https://github.com/scottrippey/SmartFormat.NET/wiki/Common-Pitfalls#security-exception), and we got the same reply from .NET Fiddle about 2 years ago. Looks like they don't intend to change their policy. We're very sorry about that.
