### ISSUE TITLE
Is it possible to mix format placholder

### ISSUE THREAD

**Issue by Genfood** [scottrippey/SmartFormat.NET#106]
If I have a string like that:
`string myString = "{0}Hello I am {Name} and I am {Age} years old.{1}";`

Am I able to format this string that the output looks like this:
`"<p>Hello I am John and  I am 22 years old.</p>"`

I tried something like this:
`Smart.Format(myString, "<p>","</p>", new { Name = "John", Age = 22 });`

But the output looked like this:
`"<p>Hello I am  and I am  years old.</p>"`

Does anyone have a tip for me or does this even work?

**Comment by axunonb** [comment]
Your working with numbered selectors, so 
```"<p>"``` is arg 0
```"</p>"``` is arg 1
```new { Name = "John", Age = 22 }``` is arg 2
You may mix with named arguments like this:
```Csharp
var myString = "{0}Hello I am {2.Name} and I am {2.Age} years old.{1}";
Smart.Format(myString, "<p>", "</p>", new { Name = "John", Age = 22 });```

**Comment by Genfood** [comment]
Thank you it works!
