### ISSUE TITLE
Formatter removes back slashes

### ISSUE THREAD

**Issue by richardspence** [scottrippey/SmartFormat.NET#107]
## Summary
The formatter is incorrectly parsing out backslashes when it should leave them in place.

## Example:
Given this input: `-property vvc=\"AnaExp_ForayApp\"` it renders `-property vvc="AnaExp_ForayApp"`

```csharp
var formatter = Smart.CreateDefaultSmartFormat();
formatter.Settings.FormatErrorAction = SmartFormat.Core.Settings.ErrorAction.MaintainTokens;
var template = @"-property vvc=\""AnaExp_ForayApp\""";
var actual = formatter.Format(template, new { });
actual == template // false
```

**Comment by axunonb** [comment]
Does this "parsing out" always occur, or only with specific data sources or formatters?
A working sample would help to sort this out.

**Comment by richardspence** [comment]
Updated with the full C# statement.

**Comment by axunonb** [comment]
Thanks for the sample.
In your case the settings must be changed to
```Csharp
formatter.Settings.ConvertCharacterStringLiterals = false; 
```
to achieve the desired result. The default setting is ```true```. The setting was introduced, in order to process templates with character string literals which are read from a file.

**Comment by axunonb** [comment]
Did this setting resolve your issue?

**Comment by richardspence** [comment]
It did, changing that setting got what I was looking for.  This issue can be closed - thanks for following up!
