### ISSUE TITLE
Complex boolean logic for strings

### ISSUE THREAD

**Issue by RichardWright** [scottrippey/SmartFormat.NET#14]
Hi

Currently you can assess a string using the smart formatter and decide it's usage like so; 

{Keywords: {}|}

I was wondering if in the future more complex logic could be used so something like the below could be used;
{Keywords && Location: some example test|} 

Currently I have a boolean return from a property which does this assessment for me so my format is still neat but I would love to get this all inline. 

Love the library btw, it's really helped cut down my codebase.

Thanks!

**Comment by scottrippey** [comment]
With #43, it will be somewhat easier to manage this using nested scopes.  For example, you could do something like:  
`{Keywords:{Location: {Keywords} {Location}| (nothing) }| (nothing)}`
