### ISSUE TITLE
Change the default behavior of Smart.Default.AddExtensions

### ISSUE THREAD

**Issue by jgauffin** [scottrippey/SmartFormat.NET#17]
I agree. Custom extensions should always be executed before the built in ones. else they would not be called for common data types.

I've created a Date extension which was not being called when following the wiki guideline:

    Smart.Default.AddExtensions(new DateFormatter());

However, if I do this:

    Smart.Default.FormatterExtensions.Insert(0, new DateFormatter());

everything works OK. But many new users might not explore the library to discover that. Insert custom extensions before the default ones.

**Comment by scottrippey** [comment]
Fixed in upcoming V1.2
