### ISSUE TITLE
Nuget package contains .NET40 dll

### ISSUE THREAD

**Issue by RichardWright** [scottrippey/SmartFormat.NET#20]
Hi

I just used the latest version of SmartFormat in a .Net 3.5 project and the dll from the .Net 3.5 profile doesn't seem to be a valid .Net 3.5 dll? The runtime referenced in the properties of the reference in the project is set to 4.0. Just thought I'd let you know.

Thanks

R

**Comment by scottrippey** [comment]
Fixed in release-management branch.
