### ISSUE TITLE
Partial Templates Support

### ISSUE THREAD

**Issue by adeel41** [scottrippey/SmartFormat.NET#33]
Hi,

I think SmartFormat should support partial content so that you don't have to specify content within {} instead just supply the partial content id and then some where else define the partial content id with the content. For example, this is what you do currently

<pre> {IsHuman: <blockquote>I am a human</blockquote>|<strong>I am an alien</strong>} </pre>

but I think it will be more readable if we can do this instead

<pre>{IsHuman:  {@HumanContent} | {@AlienContent} }</pre>

and then somewhere in the text you define these partial contents like

<pre>
{@ HumanContent}
blockquote>I am a human</blockquote>
{/@ HumanContent }

{@ AlienContent}
<strong>I am an alien</strong>
{/@ AlienContent}

</pre>

The reason is I don't want to mix my html in smart format. (may be it is just me). Syntax could be anything but that's what I thought of.

**Comment by andymac4182** [comment]
I like the idea of the RegisterTemplate syntax. It works similar to the way AngularJS handles it. The other thing might be to support a default set of templates and an injectable set of templates if you wanted. Personally I would only ever need one set but maybe people will need more in the future. 

https://docs.angularjs.org/api/ng/service/$templateCache

**Comment by scottrippey** [comment]
Ok, I'm actually finished with this in the `template-formatter` branch!
Here's the gist of it:

```c#
// Add extension:
var templates = new TemplateFormatter(Smart.Default);
Smart.Default.AddExtensions(templates);

// Register templates:
templates.Register("humanTemplate", " Human { Name } ");
templates.Register("alienTemplate", " Alien { Species } ");

// Use the templates:
Smart.Format("{0.IsHuman:  {0:template:humanTemplate}  |  {0:template:alienTemplate}  }", character);

**Comment by scottrippey** [comment]
Available in Release v1.6

**Comment by adeel41** [comment]
:+1:

**Comment by scottrippey** [comment]
Just wrote some quick docs: https://github.com/scottrippey/SmartFormat.NET/wiki/TemplateFormatter
