### ISSUE TITLE
"Named Formatters" - Improved syntax for choosing the formatter

### ISSUE THREAD

**Issue by scottrippey** [scottrippey/SmartFormat.NET#42]
I have a proposition for an improved syntax for SmartFormat, and want feedback before jumping in.

1. Explicitly choose the formatter by name.  Examples:  
  `{0:plural:singular|plural}`  
  `{0:choose:{}|null}`  
  `{0:list:{}|,}`  
  `{0:timespan:}`  
  `{0:default:N2}`
1. The formatter can take options.  Examples:  
  `{0:plural(en):singular|plural}`  
  `{0:choose(Male,Female):his|her}`  
  `{0:choose(<0,0,>0):negative|zero|positive}`  
  `{0:list(5):{}|,|, and |, and {} more}`  
  `{0:timespan(noless week):}`  

My thoughts:
* Explicit formatters make the template MUCH more readable -- to the point where I might want to make them mandatory.  But for now, it will be easy to make them optional, which lets us be backwards compatible.
* The "formatter options" appear between the parenthesis, and are comma-delimited.  They're free form -- they're just passed as strings to the formatter.  This ability greatly improves the syntax for `choose` and `list`, and enables `plural` to specify the ruleset.  
* The "format templates" appear after the 2nd colon, and are pipe-delimited.  They behave the same way as they do now.  
* Before, the "options" and "templates" (at least for `choose` and `list`) were intermingled, and the syntax was way too complicated.  This syntax will be much easier to document, and makes much better sense.

We started this discussion in #16, so I wanted to get feedback before I started these improvements.  
I think I'd like to target v1.3 for this one, since it's such a significant change.

**Comment by scottrippey** [comment]
Well, implementing this wasn't too difficult.  I've committed to the named-formatters branch, along with a ton of unit tests.  
I really like the results, and I think this will be a great move for the library.  
I'll be looking at creating some releases soon, so that these features will be available.

**Comment by scottrippey** [comment]
@SeriousM I'd like to know what you think about the following changes.

1. In the "named-formatters" branch, I implemented this feature. It's backwards compatible, but it only adds a few minor improvements.
2. In the "named-formatters-refactor" branch, I did a ton of "cleanup" work.  I refactored the way Extensions work, I changed namespaces, I paved the way for future work.  The Extensions are not backwards compatible, but the format syntax still is. 
3. I'm thinking of making "named-formatters" mandatory.  The syntax looks, and feels, so much cleaner, and way less "magical".  The formatters would be refactored to be extremely simple, and it would be very easy to document everything.  I feel like this is the right way to go, but obviously it's not backwards compatible.  

So, I'm wondering how these 3 improvements should be "rolled out".  
I'm thinking that since (1) is backwards compatible, it can be rolled out without hesitation.  It doesn't add a lot of functionality, but it definitely paves the way for better extensions.  
But (2) will break anyone who created custom extensions.  Is that anyone?  How many people are actually rolling their own?  It's probably not worth worrying about, but since it's breaking, it'll need a version bump.  
And finally, (3) is obviously the most drastic -- it's not at all backwards compatible.  Easy enough to upgrade though.  But, I feel like the library would be much better off to go down this path.  I just need someone to corroborate this idea with me.

**Comment by SeriousM** [comment]
@scottrippey I think like you.
(1) can be rolled out without problems.
(2+3) can be put into a major version bump because the named thingy is changing the way how SmartFormat works.

just a reference: http://semver.org/

**Comment by scottrippey** [comment]
(3) I'm having doubts about making the name mandatory.  I really like the simplicity and brevity of `"There {0:is|are} {0} {0:item|items} remaining"`, so perhaps I need to think about what parts are giving me trouble.

**Comment by scottrippey** [comment]
(1) has added features.  This should be v1.3.

(2) is a refactor & cleanup of the Extensions API, but the formatting syntax stays the exact same.
So I'm not really sure what I want to do about that!
I don't want to do SmartFormat 2.0, because I don't fully agree with semver. I feel like the first number should be a "Product number", and represents radical changes.
These Extension API changes will break any extensions, but they're not radical changes at all, just a nice improvement and refactoring.

So I'm thinking of slating those changes for v1.4.

**Comment by SeriousM** [comment]
lets continue with 1+2 for now and open another issue only for 3, ok?

**Comment by scottrippey** [comment]
Well, it's been a fun week getting back into this project.  I've committed all my pending changes, and released v1.3, v1.4, and v1.5!
