### ISSUE TITLE
Paranthesis in the output text results in empty string

### ISSUE THREAD

**Issue by chandmk** [scottrippey/SmartFormat.NET#45]
Smart.Format("{A:plan(s)|bar}", new{ A = true });

expected:  plan(s)
result: empty string

**Comment by scottrippey** [comment]
This looks like an issue with the Parser for "named formatters" ...
I'll create a unit test.  Shouldn't be hard to fix.

**Comment by scottrippey** [comment]
Fixed in v1.6.1
