### ISSUE TITLE
Serilog library integration

### ISSUE THREAD

**Issue by LSTANCZYK** [scottrippey/SmartFormat.NET#49]
Take a look at this nice logging library here:
https://github.com/serilog/serilog

I am using both for my logging and would like to suggest you perhaps take advantage of ideas or implementation of that library. Honestly it is sometimes confusing to me which string formatting i am supposed to use. it is my little pipe dream of having both libraries using the same syntax

**Comment by scottrippey** [comment]
Well, looking at their template syntax, it does look very similar.  Example:
```
log.Information("Processed {@SensorInput} in {TimeMS:000} ms.", sensorInput, processingTimeMs);
```

However, functionally, this is extremely different from SmartFormat.
1. This does not use "named placeholders".  You could change `"{@SensorInput}"` to `"{@AAAA}"` and it'd be fine.  Instead, in Serilog, placeholders must be in the same order as the arguments.  
2. In Serilog, `"@"`, `"SensorInput"`and `"TimeMS"` are actually *describing* how to serialize `arg[0]` and `arg[1]` in the log.

As far as SmartFormat is concerned, \#1 is a pretty extreme difference; it works great for logging, but would be absolutely terrible for localization. 

If you integrated SmartFormat into Serilog (eg. via extension methods), you'd lose much of Serilog's advanced logging capabilities.  You'd just be logging strings, not objects.

**Comment by scottrippey** [comment]
The only way you *might* be able to take advantage of both of them would be to create a custom `IOutput` for SmartFormat.  The `IOutput` object is responsible for writing the string data as it's processed, and it has full access to the current "context".  So, it's possible that the `IOutput` could write the string *and* the objects to Serilog, if Serilog has an API that doesn't use the template.
