### ISSUE TITLE
Change default ErrorAction behavior to ThrowError

### ISSUE THREAD

**Issue by scottrippey** [scottrippey/SmartFormat.NET#51]
In "Release" mode, the default `ErrorAction` is `Ignore`. 
This often results in a lot of confusion, especially since NuGet delivers the Release build. 
 So, a better default `ErrorAction` should be chosen. 

Choices are `Ignore`, `ThrowError`, `MaintainTokens`, or `OutputErrorInResult`.  

In "Debug" mode, the default `ErrorAction` is `ThrowError`, which is appropriate.

**Comment by scottrippey** [comment]
I think that `OutputErrorInResult` might be the best choice, or perhaps `MaintainTokens`.
@SeriousM Any opinion?

**Comment by mikasoukhov** [comment]
Hi Scott! I've do some details into closed issue https://github.com/scottrippey/SmartFormat.NET/issues/50 Think the problem in SmartFormat still is

**Comment by mikasoukhov** [comment]
ThrowError. Release mode and Debug shouldn't have different behaviors except logging level and performance.

**Comment by scottrippey** [comment]
@mikasoukhov That's a really good recommendation.  I agree, there shouldn't be a difference,  My original justification was that I wanted Release mode to be very forgiving.  However, now that it's on NuGet in Release mode, people are debugging with it in Release mode, which is a bad experience.  
I think I'll change the default to ThrowError, because that should be the most helpful and the expected default behavior.

**Comment by axunonb** [comment]
Formatter and Parser have ErrorAction = ErrorAction.Ignore in debug and release configuration now: 
https://github.com/scottrippey/SmartFormat.NET/commit/942e33417cccf5bc8e695d739ff381ea62135ddc
Subscribe to events OnFormattingFailure of SmartFormatter or OnParsingFailure of Parser in order to register ALL errors (not only the first) while not throwing an exception.
