### ISSUE TITLE
Signed version of nu-get package

### ISSUE THREAD

**Issue by LSTANCZYK** [scottrippey/SmartFormat.NET#54]
Can you please add SNK to the dll in the nuget package?

**Comment by SeriousM** [comment]
Just the snk?
Am 23.04.2015 00:06 schrieb "LSTANCZYK" <notifications@github.com>:

**Comment by christso** [comment]
Hi, I get the error "Could not load file or assembly 'SmartFormat, Version=1.6.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)" when I try to use it in another project that is strong-named. Can you please strong-name your assembly?

**Comment by SeriousM** [comment]
As proposed from another user or another project of mine:

You can use the [StrongNameSigner](https://github.com/brutaldev/StrongNameSigner) to sign it your self.
