### ISSUE TITLE
Overrided properties throws exceptions.

### ISSUE THREAD

**Issue by mikasoukhov** [scottrippey/SmartFormat.NET#57]
class Base
{
    public virtual int Prop1 { get; set; }
}

class Derived : Base
{
    public override int Prop1
    {
        set { }
    }
}

// usage code
Smart.Format("{Prop1}", new Derived { Prop1 = 10 }));

Unhandled Exception: SmartFormat.Core.Formatting.FormattingException: Error parsing format string: Could not evaluate the selector "Prop1" at 1 {Prop1}-^

**Comment by scottrippey** [comment]
What do you think the correct behavior would be?

**Comment by axunonb** [comment]
The derived class only has a setter. This is the reason why currently Smart.Format cannot read the value. My answer to the question, what should be the default behavior is: Follow the c# reference. The base class member must be used. So I'm sorry to confirm this is a bug that should be addressed.

**Comment by axunonb** [comment]
Issue fixed with commit https://github.com/scottrippey/SmartFormat.NET/commit/6f5cecb76bef6cee11ead32b1d83d41c1218aa92
