### ISSUE TITLE
Help Request: Using SmartFormat.NET to format complex object properties.

### ISSUE THREAD

**Issue by johnannis** [scottrippey/SmartFormat.NET#58]
I just found this amazing library today and I have a use case where I currently use reflection to iterate over the properties of a complex object and format the property name and value into strings that then written to a log file for troubleshooting. The method listed below is my current implementation which is a method on my BaseClass object which all other objects in my project inherit from. While I use this function extensively throughout my projects I would much rather have a simple one or two line alternative that would make it easier for the others to read/use when implementing objects created from my base object. Does SmartFormat.NET provide the syntactic sugar for something similar in functionality, either native or via an extension method?

John

```cs
/// <summary>
/// Provides a formatted output of all object properties and values using reflection.
/// Example: {"PropertyA" : "PropertyAValue"}, {"PropertyB" : "PropertyBValue"}
/// </summary>
/// <returns>
/// Formatted string of property names/values
/// </returns>
public new string ToString()
{
    const int itemsPerLine = 5;

    var t = GetType();
    var props = t.GetProperties();
    var className = t.Name;

    var returnValue = Environment.NewLine + className + Environment.NewLine;

    var propertiesGroup = from i in Enumerable.Range(0, props.Count())
                            group props[i] by i / itemsPerLine;

    var lastProperty = props.Last();
    foreach (var property in propertiesGroup)
    {
        foreach (var propertyInfo in property)
        {
            var value = propertyInfo.GetValue(this, new object[] { });

            returnValue += "{\"" + propertyInfo.Name + "\" : \"" + value + "\"}";

            if (!propertyInfo.Equals(lastProperty))
                returnValue += ", ";
        }
        returnValue += Environment.NewLine;
    }
    return returnValue;
}
```

Apologies this is my first post to Github and I was not able to figure out how to submit this item and apply the help tag. Can a moderator/admin please tag this post as a help request?

**Comment by scottrippey** [comment]
John,
I'm not sure if SmartFormat is designed to do what you're trying to do.  
It sounds like you're trying to serialize your object to your log.  SmartFormat is designed to format objects into strings, but it requires a template, which helps if you know all the property names beforehand.
However, SmartFormat will not help you to iterate through all the properties.  That'll be up to your own code.

**Comment by scottrippey** [comment]
Here's one way I could envision SmartFormat helping you: 
1. Gather a list of name/value pairs, using your reflection code above.
2. Use a SmartFormat template to list out all name/value pairs, using a template.

Here's an attempted example:
```cs
public new string ToString()
{
    const int itemsPerLine = 5;

    var t = GetType();
    var className = t.Name;

    var props = t.GetProperties();

	// Get all name/value pairs:
	var properties = propertiesGroup.SelectMany(properties => properties)
		.Select(propertyInfo => new { 
			name = propertyInfo.Name,
			value = propertyInfo.GetValue(this, new object[] { })
		});
	
	// Output the data using this template:
	return Smart.Format("\n{className}\n{properties: {name}: {value}|, }", new { className, properties });
}
```

The template isn't exactly right, but I didn't want to clutter the code with a bunch of escaped `{}` braces.

**Comment by johnannis** [comment]
Scott,
  Thank you for your quick reply and proposed solution. I had not given any consideration to using Linq to gather a KVP collection as you posted in your solution. Going that route is a much cleaner solution than what I had originally. On a side note this approach got the rusty old gears in my bain turning again on how to improve an issue I have with an MVC ActionFilter on another project as well.

Thank you,
John

**Comment by scottrippey** [comment]
Glad to have helped.  Linq's ability to simplify problems sure is awesome.  
One other thought that I had; maybe you should consider a [JSON serializer](http://www.newtonsoft.com/json), if you're looking for a quick and easy way to dump an object into the log.
