### ISSUE TITLE
Help Request: DateTime Math Possible?

### ISSUE THREAD

**Issue by mhsimkin** [scottrippey/SmartFormat.NET#60]
Is it possible to do math on DateTime objects?

Given the following:
Start: DateTime
End: DateTime

I'm looking to do the following operations:
{{Start-1}}
{{End-Start}}

Is this possible?

Thanks

marc

**Comment by scottrippey** [comment]
No, that's not possible.  The expression (or Selector as we call it) is supposed to remain simple, and does not support any logic.  It just supports getting properties, or can call a parameterless method (such as `ToString` or `ToUpper`, but that's it.
Mostl other logic should be handled by code.  For example:

    Smart.Format("{Start} {End} ({Duration})", new { Start, End, Duration = End-Start });
