### ISSUE TITLE
Invalid character in the selector

### ISSUE THREAD

**Issue by danielgarcia78** [scottrippey/SmartFormat.NET#62]
Im trying to generate an HTML mail code using format but im gettin an Invalid character in the selector error, this is the string because of the style section that uses {}, how can i handle this issue?

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
    <style type="text/css">
        p.MsoNormal {
            margin-bottom: .0001pt;
            font-size: 12.0pt;
            font-family: "Times New Roman",serif;
            margin-left: 0cm;
            margin-right: 0cm;
            margin-top: 0cm;
        }

        table.MsoNormalTable {
            font-size: 11.0pt;
            font-family: "Calibri",sans-serif;
        }

        a:link {
            font-family: "Verdana",sans-serif;
            color: #FF6600;
            text-decoration: none;
            text-underline: none;
            text-decoration: none;
            text-line-through: none;
        }
    </style>
</head>
<body>
    <p class="MsoNormal" style="margin-bottom: 12.0pt">NUEVA SOLICITUD DE 2Ayuda</p>
    <table border="0" cellpadding="0" class="MsoNormalTable" style="mso-cellspacing: 1.5pt; mso-yfti-tbllook: 1184; mso-padding-alt: 0cm 0cm 0cm 0cm">
        <tr style="mso-yfti-irow: 0; mso-yfti-firstrow: yes">
            <td style="padding: 0cm 0cm 0cm 0cm">
                <p class="MsoNormal"><b>Solicitud:</b><o:p></o:p></p>
            </td>
            <td style="padding: 0cm 0cm 0cm 0cm">
                <p class="MsoNormal">{id_Solicitud}</p>
            </td>
        </tr>
        <tr style="mso-yfti-irow: 1">
            <td style="padding: 0cm 0cm 0cm 0cm">
                <p class="MsoNormal"><b>Solicitante:</b><o:p></o:p></p>
            </td>
            <td style="padding: 0cm 0cm 0cm 0cm">
                <p class="MsoNormal">{NomSolicita}</p>
            </td>
        </tr>
        <tr style="mso-yfti-irow: 2">
            <td style="padding: 0cm 0cm 0cm 0cm">
                <p class="MsoNormal"><b>Titulo:</b><o:p></o:p></p>
            </td>
            <td style="padding: 0cm 0cm 0cm 0cm">
                <p class="MsoNormal">{NomSolicitud}</p>
            </td>
        </tr>
        <tr style="mso-yfti-irow: 3">
            <td style="padding: 0cm 0cm 0cm 0cm">
                <p class="MsoNormal"><b>Descripción:</b><o:p></o:p></p>
            </td>
            <td style="padding: 0cm 0cm 0cm 0cm">
                <p class="MsoNormal">{DscSolicitud}</p>
            </td>
        </tr>
        <tr style="mso-yfti-irow: 4">
            <td style="padding: 0cm 0cm 0cm 0cm">
                <p class="MsoNormal">&nbsp;<o:p></o:p></p>
            </td>
            <td style="padding: 0cm 0cm 0cm 0cm"></td>
        </tr>
        <tr style="mso-yfti-irow: 5">
            <td style="padding: 0cm 0cm 0cm 0cm">
                <p class="MsoNormal"><b>Asignado a:</b><o:p></o:p></p>
            </td>
            <td style="padding: 0cm 0cm 0cm 0cm">
                <p class="MsoNormal">{NomAsignado}</p>
            </td>
        </tr>
        <tr style="mso-yfti-irow: 6">
            <td style="padding: 0cm 0cm 0cm 0cm">
                <p class="MsoNormal">&nbsp;<o:p></o:p></p>
            </td>
            <td style="padding: 0cm 0cm 0cm 0cm">
                <p class="MsoNormal">
                    <b>Correo:</b> <a href="mailto:{TxtCorreoAsignado}"><span style="font-family: &quot; Verdana&quot; ,sans-serif">{TxtCorreoAsignado}</span></a><o:p></o:p>
                </p>
            </td>
        </tr>
        <tr style="mso-yfti-irow: 7">
            <td style="padding: 0cm 0cm 0cm 0cm">
                <p class="MsoNormal"><b>Estatus:</b><o:p></o:p></p>
            </td>
            <td style="padding: 0cm 0cm 0cm 0cm">
                <p class="MsoNormal">{nomEstatus} <i><span style="font-size: 8.0pt">({dscEstatus})</span></i><o:p></o:p></p>
            </td>
        </tr>
        <tr style="mso-yfti-irow: 9; mso-yfti-lastrow: yes">
            <td style="padding: 0cm 0cm 0cm 0cm">
                <p class="MsoNormal"><b>Fecha Alta:</b><o:p></o:p></p>
            </td>
            <td style="padding: 0cm 0cm 0cm 0cm">
                <p class="MsoNormal">{fecAlta}</p>
            </td>
        </tr>
    </table>
</body>
</html>

**Comment by gawelczyk** [comment]
I have got the same problem. It still produces output but I can see many errors in Debug window.
Is there any workaround?

**Comment by scottrippey** [comment]
Yes, the issue is the `{ ... }` style blocks in your HTML. There are 2 potential solutions ...
1. You can escape the style blocks like `\{ ... \}`
2. You can enable the following error action:  `Smart.Default.ErrorAction = ErrorAction.MaintainTokens`, which will ignore errors and just keep the text as-is.
