### ISSUE TITLE
No documentation on setting the default source extension

### ISSUE THREAD

**Issue by ciphernemo** [scottrippey/SmartFormat.NET#66]
I ran into this issue when trying to get this project rolling in my app by downloading the source here and building it without fully reading the wiki. I was using SmartFormatter.Format instead of using Smart.Format, so it was throwing the error "No source extensions are available. Please add at least one source extension, such as the DefaultSource". On that note, I eventually wiped my manual install and used your nice NuGet package instead.

Any ways, it was a moment of /facepalm when I realized my issue. Perhaps you could add this into the wiki somewhere? And perhaps solutions to all of the thrown errors?

Thanks for an amazing little project. I'm using it now and it's quick and convenient. :+1:

**Comment by axunonb** [comment]
Yes, you're absolutely right. There is a note now in the Wike at https://github.com/scottrippey/SmartFormat.NET/wiki/Home
