### ISSUE TITLE
Getting item from array

### ISSUE THREAD

**Issue by virus2016** [scottrippey/SmartFormat.NET#67]
Maybe I am missing something here.

{
  "total_population": [
    {
      "date": "2015-10-07",
      "population": 63938661
    },
    {
      "date": "2015-10-08",
      "population": 63939630
    }
  ]
}

Using SmartFormat.NET, I was hoping to get the 2nd array item. I thought I could do this:

Smart.Format("Total Population from the 2015-10-08 was {total_population[1].population}, abovejsondata);

Can anyone help?

Cheers,

**Comment by scottrippey** [comment]
Please create a DotNetFiddle.net to recreate the issue next time.
I've recreated your example here, and everything seems to work correctly: https://dotnetfiddle.net/4yHwJ9
However, I'm using C# Anonymous objects, and it sounds to me like maybe you're using some sort of JSON-based data.  So perhaps your JSON data structures are not supported by the default extensions, and perhaps they do not implement the interfaces that are supported by SmartFormat (ie. `IDictionary`, `ICollection`).
If you can recreate the issue in DotNetFiddle.net then perhaps we can discuss more.  Thanks!
