### ISSUE TITLE
Escaping the Pipe Character

### ISSUE THREAD

**Issue by andyfensham** [scottrippey/SmartFormat.NET#68]
How do I escape the Pipe Character in a template.

I want to output 

Field1|Field2|Field3

**Comment by AdhamAwadhi** [comment]
Me too, How we can do this?

**Comment by AdhamAwadhi** [comment]
I write custom choose formatter to solve this issue, look code below (if there is any suggestion please email me:adhamawadhi@gmail.com)

`
using System;
using System.Collections.Generic;
using SmartFormat.Core.Extensions;
using SmartFormat.Core.Parsing;
using System.Linq;

namespace SmartFormat.Extensions
{
    /// <summary>
    /// This is custom choose formatter to set a split char, you must write first char of FormatterOptions to set it as split char. like {0:cc(`null): N/A ` {}}<br/>
    /// I made this to write Pipline char | in choose options.
    /// </summary>
    /// <seealso cref="SmartFormat.Core.Extensions.IFormatter" />
    public class ChooseFormatterCustomSplitChar : IFormatter
    {
        private string[] names = { "choosec", "cc" };
        public string[] Names { get { return names; } set { names = value; } }

        private char splitChar = '|';
        public char SplitChar { get { return splitChar; } set { splitChar = value; } }

        public bool TryEvaluateFormat(IFormattingInfo formattingInfo)
        {
            if (formattingInfo.FormatterOptions == "") return false;
            splitChar = formattingInfo.FormatterOptions.ElementAt(0);
            var formatterOptions = formattingInfo.FormatterOptions.Substring(1);

            var chooseOptions = formatterOptions.Split(splitChar);
            var formats = formattingInfo.Format.Split(splitChar);
            if (formats.Count < 2) return false;

            var chosenFormat = DetermineChosenFormat(formattingInfo, formats, chooseOptions);

            formattingInfo.Write(chosenFormat, formattingInfo.CurrentValue);

            return true;
        }

        private static Format DetermineChosenFormat(IFormattingInfo formattingInfo, IList<Format> choiceFormats, string[] chooseOptions)
        {
            var currentValue = formattingInfo.CurrentValue;
            var currentValueString = (currentValue == null) ? "null" : currentValue.ToString();

            var chosenIndex = Array.IndexOf(chooseOptions, currentValueString);

            // Validate the number of formats:
            if (choiceFormats.Count < chooseOptions.Length)
            {
                throw formattingInfo.FormattingException("You must specify at least " + chooseOptions.Length + " choices");
            }
            else if (choiceFormats.Count > chooseOptions.Length + 1)
            {
                throw formattingInfo.FormattingException("You cannot specify more than " + (chooseOptions.Length + 1) + " choices");
            }
            else if (chosenIndex == -1 && choiceFormats.Count == chooseOptions.Length)
            {
                throw formattingInfo.FormattingException("\"" + currentValueString + "\" is not a valid choice, and a \"default\" choice was not supplied");
            }

            if (chosenIndex == -1)
            {
                chosenIndex = choiceFormats.Count - 1;
            }

            var chosenFormat = choiceFormats[chosenIndex];
            return chosenFormat;
        }
    }
}
`
