### ISSUE TITLE
Padding in smartformat

### ISSUE THREAD

**Issue by jogibear9988** [scottrippey/SmartFormat.NET#69]
Is there a way to Pad to a derfined length? For Example I have a integer Variable, and I want that the Var is always displayed as "...123" means 6 Charactes, padded with "." in front?

**Comment by axunonb** [comment]
You can do alignment with SmartFormat.Net in the same way like with string.Format, and both are limited to using spaces instead of dots (or other chars)
Have a look at the "alignment" example at https://msdn.microsoft.com/de-de/library/system.string.format(v=vs.110).aspx
