### ISSUE TITLE
Single bracket issue

### ISSUE THREAD

**Issue by gdefombelle** [scottrippey/SmartFormat.NET#71]
When parsing with non balanced brackets such as "};" the String.Format return an empty string.
Also when parsing a line ending by } such as "Struct}" The String.Format return a weird string

**Comment by axunonb** [comment]
```csharp
Smart.Default.Parser.ErrorAction = ErrorAction.ThrowError;
Smart.Format("Struct}")
```
results in a parsing exception "Format string has too many closing braces"
```csharp
string.Format("Struct}")
```
throws a FormatException.
Both handle unbalanced curly braces in a similar way.
