### ISSUE TITLE
How do I combine extensions?

### ISSUE THREAD

**Issue by rhyek** [scottrippey/SmartFormat.NET#72]
I have a custom extension called "words" that can convert a number to text. So if I do {Age:words()} would get something like "twenty-seven" instead of 27. I would like to combine this with another extension I have called "capitalize" so when doing {Age:words():capitalize()} I would get "TWENTY-SEVEN". This does not work, however. Is this possible?

**Comment by axunonb** [comment]
No, this does not work, formatter extensions cannot be linked. In the given example you could add an argument to your words extension, e.g. {Age:words(lc)} or {Age:words(uc)}, though. I'd appreciate if you shared your words extension :)
