### ISSUE TITLE
ListFormatter inside ChooseFormatter bug

### ISSUE THREAD

**Issue by j055** [scottrippey/SmartFormat.NET#74]
Hi

I'm trying to create a format which deals with the possibility of an empty list but get unexpected results. The following test fails:

```
[TestMethod]
public void ListFormatterInsideChooseTest()
{
    var list = new List<string> { "Donald", "Hillary" };
    var result = Smart.Format("{Count:choose(0):absent|{0:{}|, | and }}", list);
    Assert.AreEqual("Donald and Hillary", result);

    //Fails: Donald and }Hillary

    /*
    SmartFormat.Core.Parsing.ParsingErrors: The format string has 1 issue:
    Format string is missing a closing brace
    In: "{Count:choose(0):absent|{0:{}|, | and }}"
    At:  ----------------------------------------^
    */
}

```

Thanks
Andrew

**Comment by axunonb** [comment]
This in an ambiguity which the parser cannot resolve. It's about the }} at the end of the format string:
a) It could be an escaped closing curly brace
b) It could (and you expect it to) be the end of the list formatter
If you insert a space between the two ending curly braces everything works fine.
This is a limitation of the concept.
