### ISSUE TITLE
Introduce Korean extension

### ISSUE THREAD

**Issue by sublee** [scottrippey/SmartFormat.NET#79]
Hi Scott,

My team is making [a SmartFormat.NET extension for Korean](https://github.com/what-studio/SmartFormat.NET-Korean).  Korean, my mother tongue, has own special linguistic logic beyond the Indo-European languages.

How about you introduce the extension as an example of custom extensions on the wiki of this project?

**Comment by axunonb** [comment]
Thanks, this is a good example about language support. The extension, however, requires further modifications, not just the KoreanFormatter. So it's not exactly following the extensions design. Good work though, keep it up.

**Comment by sublee** [comment]
@axunonb What was wrong?  If you let us know, we will fix it.

**Comment by axunonb** [comment]
There was nothing wrong about your extension. Frankly, not speaking Korean I only have a very rough understanding what it is actually doing. Will it work with the latest source of the Master branch?
