### ISSUE TITLE
How to escape / encode a colon for (date)time?

### ISSUE THREAD

**Issue by RobThree** [scottrippey/SmartFormat.NET#81]
See [Extra Features](https://github.com/scottrippey/SmartFormat.NET/wiki#extra-features)

> `Smart.Format("{0} {0:N2} {1:yyyy-MM-dd}", 5, new DateTime())`

What if I wanted to do `yyyy-MM-dd HH:mm:ss`? I can't find a way to encode/escape the colons.  `yyyy-MM-dd HH\:mm\:ss` doesn't work.

**Comment by axunonb** [comment]
Formatting DateTime requires the "named formatter" with its name "default" because of the additional colons in the time format, e.g.: SmartFormatter.Format("{Now:default:dd.MM.yyyy hh:mm:ss}", DateTime.Now);

**Comment by RobThree** [comment]
> It was aksed quite some time ago, but still:

Long enough for me to not even remember what project I was (considering) using it on 😝 
I'll see if I can find it and if your response helps. Gimme a few days though, I have a long weekend this week 👍
