### ISSUE TITLE
Multi-pass formatting

### ISSUE THREAD

**Issue by saguiitay** [scottrippey/SmartFormat.NET#83]
Is it possible to format a string using multiple passes in an efficient matter?

For example, I'd like to replace the following code to use SmartFormat.Net:

``` csharp
var template = "... {Placeholder1} ... {Placeholder2} ...";
var result = template.Replace("{Placeholder1}", val1);
result = result.Replace("{Placeholder2}", val2);
// Many other placeholders and values replaces
```

The above code is very inefficient performance wise (scans the template multiple times) and memory wise (generate all the partially formatted strings). Assuming that the various values are taken from different sources/objects, I'd love to be able to do something along the lines of:

``` cs
var template = "... {Placeholder1} ... {Placeholder2} ...";
var partiallyFormatted = template.SmartFormat("{Placeholder1}", val1); // or perhaps template.SmartFormat(val1); 
partiallyFormatted = partiallyFormatted.SmartFormat("{Placeholder2}", val2);
// Many other placeholders and values replaces
var result = partiallyFormatted.SmartFormat();
```

Would that be feasible?

**Comment by axunonb** [comment]
Hi
Yes, the string.Replace(...) snippet is unefficient indeed.
I'm not sure what exactly you'd like to achieve, but it looks like this is what you're after
``` csharp
const string baseTemplate = "This is {ph-1}, and this is {ph-2}";

var changePlaceholders1 = new Dictionary<string, object>() { { "ph-1", "{Placeholder1}" }, { "ph-2", "{Placeholder2}" } };
var changePlaceholders2 = new Dictionary<string, object>() { { "ph-1", "{AnotherPlaceholder}" }, { "ph-2", "{AnyPlaceholder}" } };

var result = Smart.Format(baseTemplate, changePlaceholders1);
Console.WriteLine(result); // This is {Placeholder1}, and this is {Placeholder2}
result = Smart.Format(baseTemplate, changePlaceholders2);
Console.WriteLine(result); // This is {AnotherPlaceholder}, and this is {AnyPlaceholder}
```
Should be considerably faster than string.Replace(...).

**Comment by saguiitay** [comment]
You suggestion makes sense.

The thing I'm trying to achieve is to "build up" my result step by step. I'll start with a template, and bit by bit I'll replace the various placeholders with the correct values...
