### ISSUE TITLE
Accessing SelectorText property

### ISSUE THREAD

**Issue by fruitbatinshades** [scottrippey/SmartFormat.NET#85]
Whilst in debug I can see the SelectorText property but cannot access it. I am trying to add an extension to translate labels etc. How can I access this property?

Many Thanks

![image](https://cloud.githubusercontent.com/assets/318746/24009175/0b1cd7ba-0a6c-11e7-80be-d423bda06d1a.png)

**Comment by axunonb** [comment]
The expected argument must be an object implementing ```IFormattingInfo```. You see the SelectorText in debug mode, in case the argument also implements ```ISelectorInfo```, so you could use a ```cast```.

**Comment by fruitbatinshades** [comment]
Thank you axunonb.
