### ISSUE TITLE
How to get new line delimiter when templates are stored in a file

### ISSUE THREAD

**Issue by 5thHorsem4n** [scottrippey/SmartFormat.NET#86]
Part of my template:
Values were {Samples:list:{Value} @ {DateTimeUtc:u}|, |, }

Instead of ', ' I would like a new line. I have a few solutions to achieve this but I would like to keep all of my text formatting in the file. I would prefer not to do things like add the new line character to the object, or format the lines ahead of time with the new line character. 

I want something like:
Values were {Samples:list:{Value} @ {DateTimeUtc:u}|{System.Environment.NewLine} |{System.Environment.NewLine }}

This results in just white space but something similar is what I am trying to achieve

**Comment by axunonb** [comment]
You mentioned a file but there was no sample attached and there was also no sample for the list. So I can just guess that you would like to have something like this: 
```Csharp
var dict = new Dictionary<string, object> {{"MyList", new List<string> {"one", "two", "three"} }, {"MyCrLfOrNot", Environment.NewLine} };
var result = Smart.Format("Values were {MyList:list:{}|, |, and }{MyCrLfOrNot}", dict);
// or for a static CrLf
res = Smart.Format("Values were {MyList:list:{}|, |, and }{1}", dict, Environment.NewLine);
// result is "Values were one, two, and three\r\n" in both cases
```
But if you want the CrLf neither as a data object nor in the format string, where should it come from?

**Comment by 5thHorsem4n** [comment]
Sorry if I was not clear.

I have a file like MyTemplate.txt, the contents of the file are:
````
Values of my sample are {Samples:list:{Value} @ {DateTimeUtc:u}|, |, }
````

If have code similar to:
````
Smart.Format(Resources.MyTemplate, sampleSet)
````
Where Resources.MyTemplate is a resource file that  contains MyTemplate.txt and sampleSet is an object that contains my samples.

Instead of delimiting with a comma I would like to use a new line. What I would like is the new like to be apart of the template in some way such as
````
Values were {Samples:list:{Value} @ {DateTimeUtc:u}|{System.Environment.NewLine} |{System.Environment.NewLine }}
````

I would prefer not to not to pass in a second parameter that is the new line or do formatting of data in my object. I want to keep all of the formatting knowledge in one place. 

If it can't be done that is fine and I will work around it.

**Comment by axunonb** [comment]
I see. So why don't you simply replace the (not working) ```System.Environment.NewLine``` with ```\r\n```?

**Comment by 5thHorsem4n** [comment]
Since it is in a file, \r\n will be the literal characters \r\n.

**Comment by axunonb** [comment]
Now fully understood. Sorry, no way meeting the restrictions. Second parameter would come closest.

**Comment by 5thHorsem4n** [comment]
Okay not a big deal, I might try writing an extension. Thank you for your time.

**Comment by axunonb** [comment]
Rethinking your issue I come to the conclusion that this could be of general interest. Did write an extension or would you like to contribute a generic extension for Smart.Format? I would be interested in the way you'd solve it.

**Comment by 5thHorsem4n** [comment]
I was pressed for time so I solved it in a crude way.  I took the ListFormatter.cs copied it and renamed it as ListFormatterNewLine.

Then I replaced the following:
````
            var itemFormat = parameters[0];
            var spacer = (parameters.Count >= 2) ? parameters[1].GetLiteralText() : "";
            var lastSpacer = (parameters.Count >= 3) ? parameters[2].GetLiteralText() : spacer;
            var twoSpacer = (parameters.Count >= 4) ? parameters[3].GetLiteralText() : lastSpacer;
````
to be:
````
            var itemFormat = parameters[0];
            var spacer = System.Environment.NewLine;
            var lastSpacer =System.Environment.NewLine;
            var twoSpacer = System.Environment.NewLine;
````
It got the job done but it is not what I would call good. 

I do like the idea of a constant extension and having the ability to register constants or overwrite existing  ones.  Depending on how complex your templates were it could be pretty slick if your template used something like {Constants.Tab} by default was '\t' but you could change it to be '   ' (4xspace) at startup.  Let me play around the idea and see how it works.

**Comment by axunonb** [comment]
With the latest commit (https://github.com/scottrippey/SmartFormat.NET/commit/7b5946a0d0cbefff63109bcd1a68e3119123b540) ```SmartObjects``` are introduced.
With SmartObjects
* all objects used for Smart.Format can be collected in one place as the first argument
* the format string can be written like each object would be the first argument of Smart.Format
* there is no need to bother from which argument a value should come from 

```
var d1 = new Dictionary&lt;string,string&gt; { {"myKey", "myValue"} };
var nl = new Dictionary&lt;string,string&gt; { {"NewLine", System.Environment.NewLine} };
var smartObj = new SmartObjects();
smartObj.AddRange(new object[] {d1, nl});
Smart.Format("{myKey}{NewLine}and more...", smartSrc);

result:
"myValue
and more"
```
This can be achieved without extensions.
Does this solve your issue?

**Comment by 5thHorsem4n** [comment]
That would work. What I would do then is build a wrapper class to add in the dictionary of constants. This would make so my consuming class does not need to know to pass on in constants dictionary.

**Comment by 5thHorsem4n** [comment]
When is the next release coming?

**Comment by axunonb** [comment]
I'm just about completing the next release for [MailMergeLib](https://github.com/axuno/MailMergeLib), so end of June could be possible.

**Comment by axunonb** [comment]
Would you like to contribute a solution for the constant issue with lists?

**Comment by 5thHorsem4n** [comment]
I would however I know I will not have enough time to do it by end of June.

**Comment by axunonb** [comment]
Better later than never :)
After all my conclusion for the best generally applicable solution was: Add a switch to the list formatter which will lead to parsing character literals (i.e. \' \" \\ \0 \a \b \f \n \r \t \v) and convert them. I guess this could even become the default behavior for the list formatter. What do you think?

**Comment by 5thHorsem4n** [comment]
It was a option I considered early on but instead of a switch use the braces.
````
{MyArr:list: {Name}| {\r\n} | {\r\n}}
````
The braces are already used in the format parsing. What would need to happen is to check the inner text to see if it starts the \. This should be safe since property names can't start with \. And if it does match then parse find what character it is.

**Comment by axunonb** [comment]
With commit https://github.com/scottrippey/SmartFormat.NET/commit/ccacca3291ecb39ea432e22c84c4e34acf71b972 literal characters (\n, \r, \t, \v etc.) in SmartFormat literals will be converted to Unicode. This is the default behavior now, but can be switched off. See the commit comment for more information. An example with the list formatter is included in the ```LiteralText``` tests.

The advantage of this approach is, that literal characters will be available as their Unicode representation in **all** formatters out of the box. Is this the kind of enhancement you were looking for?

**Comment by 5thHorsem4n** [comment]
That should work perfectly.

**Comment by axunonb** [comment]
Fine. Finally closed with commit https://github.com/scottrippey/SmartFormat.NET/commit/2d377a73caac13f4b8cbbddbe74b10f81a35e7b2 which included better performance literal characters included in the format string.
