### ISSUE TITLE
Add a "RegEx Formatter" extension

### ISSUE THREAD

**Issue by krptodr** [scottrippey/SmartFormat.NET#88]
I have a list of nested objects and I'd like to get to provide some sort of condition on it so it knows which list item to grab. 

```
Smart.Format("{User.Address.Where(Zip=55555):{Street}, {City}, {State} {Zip}}", data)
```

My list can return entirely different things depending on a foreign relationship.

**Comment by ericpyle** [comment]
I'm trying to do something similar. I'd like to apply a template to an item in a list depending upon the value of a property. But I have to repeat the template if I use choose(). 

I figure there is a way to use a complex condition (:cond:) but I can't figure out how to do that with a list.

`{mylist:list:{myproperty:choose(val1|val2):
    <template type="{myproperty}">
      <id>{anotherprop}</id>
    </template>|
    <template type="{myproperty}">
      <id>{anotherprop}</id>
    </template>}||}`

**Comment by axunonb** [comment]
@krptodr: There is no LINQ implemented into ```Smart.Format``` selectors or format strings (if this was your question).

**Comment by axunonb** [comment]
@ericpyle: Yes, definitely. You could do this with an tailored extension similar to the conditional formatter. If you find a general approach, I'm happy to include the new extension to the repository.

**Comment by ericpyle** [comment]
@axunonb Thanks for the tip. This satisfies my needs for now:

Usage
```
{value:in(val1,val2,...): format | default}
```
Or in context of list:
```
{myList:list:{value:in(val1,val2,...): format | default}||}
```
I know that in most cases SmartFormat uses `|` as an options separator but wanted to distinguish from `choose` syntax.

```
        public class InFormatter : IFormatter
        {
            private string[] names = new[] { "in" };
            public string[] Names { get { return names; } set { this.names = value; } }

            public bool TryEvaluateFormat(IFormattingInfo formattingInfo)
            {
                var options = formattingInfo.FormatterOptions.Split(',');
                var formats = formattingInfo.Format.Split('|');
                if (formats.Count == 0)
                    return true;
                if (options.Contains(formattingInfo.CurrentValue))
                    formattingInfo.Write(formats.First(), formattingInfo.CurrentValue);
                else if (formats.Count == 2)
                    formattingInfo.Write(formats.Last(), formattingInfo.CurrentValue);
                return true;
            }
        }`

**Comment by axunonb** [comment]
Cool. Would it be possible to supply a unit test for the ```InFormatter```?

**Comment by ericpyle** [comment]
I've been wondering if a regex value:matches(regex) formatter might be even better.  It would even work with "val1|val2" and regex should have decent cross platform support

**Comment by axunonb** [comment]
How would you design it? RegEx groups in connection with lists?

**Comment by ericpyle** [comment]
@axunonb I wasn't thinking about handling lists directly. I'd do it like this (untested):

**Syntax**
`{value:ismatch(regex): format | default}`
Or in context of list:
`{myList:list:{value:ismatch(regex): format | default}||}`

Where `regex` can be a simple regex string like `^val1|val2|val3$` (match whole words)

```
public class IsMatchFormatter : IFormatter
        {
            private string[] names = new[] { "ismatch" };
            public string[] Names { get { return names; } set { this.names = value; } }

            public bool TryEvaluateFormat(IFormattingInfo formattingInfo)
            {
                var regexStr = formattingInfo.FormatterOptions;
                var formats = formattingInfo.Format.Split('|');
                if (formats.Count == 0)
                    return true;
                var rgx = new Regex(regexStr);
                if (rgx.IsMatch(formattingInfo.CurrentValue))
                    formattingInfo.Write(formats.First(), formattingInfo.CurrentValue);
                else if (formats.Count == 2)
                    formattingInfo.Write(formats.Last(), formattingInfo.CurrentValue);
                return true;
            }
        }`
```
Thoughts?

**Comment by axunonb** [comment]
Agree this would be quite flexible (even more than your ```in``` extension idea) and also available under .NetStandard.
Maybe ```matches``` would be better than ```ismatch```?
Would you post a PR?
