### ISSUE TITLE
Is there a way to limit a format to inner block/parent scope, and not the outer scope?

### ISSUE THREAD

**Issue by ericpyle** [scottrippey/SmartFormat.NET#89]
`{manifest_resources:list:
    <resource size="{size}">
      {atoms:list:<atom size="{size}"/>||}
    </resource>||}`

I'd like _atom_ `size` to not inherit from _resource_ `size`, if _atom_ `size` is absent.

        [TestCase(@"{manifest_resources: [{atoms: [{}], ''size': 'size'}]}"]

As a workaround I can name them differently:

`{manifest_resources:list:
    <resource size="{size}">
      {atoms:list:<atom size="{atom_size}"/>||}
    </resource>||}`

**Comment by axunonb** [comment]
You mean conditional inheritance. I never thought about this use case, but my guess is "no". It's a bit difficult to judge without knowing which kind of data you supply to Smart.Format, and time consuming without a sample snippet.

**Comment by ericpyle** [comment]
@axunonb I'm wondering if there's a way I can make an extension that walks up FormattingInfo.Parent to see where FormattingInfo.Result gets computed from that parent CurrentValue, and try to figure out whether or not another object was queried for the property.  If not, I'll just have to make sure my data provides all the required information, and perhaps I can make an extension that detects empty strings, so I don't write out xml attributes or elements based on data with empty strings.

**Comment by axunonb** [comment]
No, in FormattingInfo you just see the result a formatter has computed, not the failure. You think this would be a generally useful feature?

**Comment by ericpyle** [comment]
Honestly, you know the bigger picture more than I do.  Here's a user story for what I've been trying to accomplish.

I want to make a template for an xml document that needs to validate with a RelaxRNG schema.  In the schema, empty elements and attributes are invalid.  So, I would like the template to be able to remove elements or attributes that are optional. Sometimes those optional elements/attributes occur in a nested folder structure, where the folder and the file (non-folder) elements can share attribute names.

So, to prevent a folder attribute value from being re-used for an optional sub-folder or file attribute, I can have the following options
1. Require the source data to always supply (possibly empty) values for the sub-folder or file attributes. Have a Formatter extension be able to detect empty values and if so don't write out the attribute.
2. Have a Formatter extension for optional attributes try to walk up parent FormattingInfo stack to try to determine whether a value was gotten from the nearest object, or from another object further up the scope.
3.  have a general setting (or Source extension?) that prevents passing values from outer scope, unless the full path to the value is specified starting from Root 0:outer_scope_field. Obviously once nesting includes a recursively nested structure (like folder/subfolders), it becomes challenging to specify the full path to a value. Likewise if a reference to a value inside a list in the outer scope is needed, that would not be easy. However, for my purposes 0:outer_scope_field is sufficent.

My second user story (not quite as important) is that I'd love to be able to quickly (using minimal data) produce a minimal xml document (with empty elements and attributes) that shows the structure that needs to be filled in to pass validation.  And I'd love to be able to quickly (using as little data as possible) to produce a full xml structure showing the optional elements and attributes that could be filled in. As a bonus... rather than having empty elements and attributes, provide the name of the field/placeholder used to fill in the document. I imagine that I could write source extensions to help accomplish this.

**Comment by ericpyle** [comment]
I think my first approach will be to override the ConditionalFormatter by checking if the current value is null or empty string otherwise let the stock ConditionalFormatter handle formattingInfo. Then my optional elements/attributes data can be set to null or empty in contexts that might otherwise inherit from the scope

**Comment by axunonb** [comment]
What you are trying to accomplish with ```Smart.Format``` is to **create** an XML file, while ```Smart.Format``` can read and output data from rather simple XML. I agree that for your use case https://github.com/beto-rodriguez/SuperXml might be a better fit than ```Smart.Format```. So why not use the strength of both libraries?
