### ISSUE TITLE
v2.1.0 assembly is not signed anymore

### ISSUE THREAD

**Issue by andreminelli** [scottrippey/SmartFormat.NET#92]
This was intended? There is nothing about this on changes.md.

This could be considered a breaking change (worthing to register) since it causes TypeLoadException on clients that updates to 2.1.0 but uses thirdy party packages which still depends on version 2.0.0, for instance.

**Comment by axunonb** [comment]
No, definitely not intended. Thanks for pointing this out. Will post an update later today.
