### ISSUE TITLE
String after Choose or Condition is lost after formatting.

### ISSUE THREAD

**Issue by proreilly** [scottrippey/SmartFormat.NET#93]
Hello! I am having great success using smart format in my project, however, have hit an issue when using the choose or condition function.

I am trying to perform a replacement in a string like:

"Tell me {0:{Gender:choose(Male:Female):his|her}} name?"

I call smart format passing an array of objects and the function evaluates correctly - but the " name?" is lost from the end of the returned string. If I do a format operation without the choose, the full string ("Tell me Male name?") is returned as expected.

Is there anything missing from my string to enable the last part of the string to be preserved?

**Comment by proreilly** [comment]
After some testing, it works as expected if the second closing "}" is removed.

**Comment by axunonb** [comment]
Yep, exactly, just like it is described on https://github.com/scottrippey/SmartFormat.NET/wiki/Choose
Happy to hear you like SmartFormat.Net. One more reason to keep it up 👍  :)
For historical reason, SmartFormat is string.Format compatible. So you maycome across issues with curly braces in more complex scenarios: https://github.com/scottrippey/SmartFormat.NET/wiki/Common-Pitfalls
I think Smart.Default.Parser.UseAlternativeEscapeChar() is usually better.
