### ISSUE TITLE
Strange behaviour with backslash followed by curly braces

### ISSUE THREAD

**Issue by seanamosw** [scottrippey/SmartFormat.NET#94]
I am getting an unexpected result when the following format and settings are used.

```csharp
var formatter = Smart.CreateDefaultSmartFormat();
formatter.Settings.ConvertCharacterStringLiterals = false;

var result = formatter.Format("\\{Test}", new { Test = "Hello" });
```

Expected Result: `Hello`
Actual Result: `{Test`

**Comment by seanamosw** [comment]
I've confirmed rolling back to 2.0.0 has the correct output

**Comment by axunonb** [comment]
For the actual result you are also using ```formatter.Parser.UseAlternativeEscapeChar()```, right?

**Comment by axunonb** [comment]
Expected result should read ```\Hello``` instead of ```Hello```

**Comment by seanamosw** [comment]
My mistake, you are right the expected output should be `\Hello`.
Thank you for the quick resolution.
