### ISSUE TITLE
UWP support

### ISSUE THREAD

**Issue by Eitilt** [scottrippey/SmartFormat.NET#97]
Is there any way to add UWP support to this? When I try to add it to my project, the package manager fails with (along with similar messages for the other architectures):
```
Package SmartFormat.Net 2.1.0.2 is not compatible with uap10.0.10586 (UAP,Version=v10.0.10586) / win10-x64. Package SmartFormat.Net 2.1.0.2 supports:
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - netstandard1.6 (.NETStandard,Version=v1.6)
```

I understand completely if there's code that relies on newer versions, but since I can add each of the three dependencies SmartFormat lists just fine, I'm wondering if it's simply an issue with there not being the proper `uap10.0` target framework.

**Comment by axunonb** [comment]
I never used ```SmartFormat.Net``` in UWP. What I understand from an answer on [StackOverflow](https://stackoverflow.com/questions/38181004/can-i-build-uwp-with-net-core):
> UWP apps will be able to use libraries you have created in .net core as long as you target the .netstandard1.6 framework moniker. 

This is the case with  ```SmartFormat.Net```.

And in a [MSDN-Blog](https://blogs.msdn.microsoft.com/dotnet/2016/05/27/making-it-easier-to-port-to-net-core/) you can read
> Whether you need to build a desktop application, a mobile app, a web site, or a micro service: you can rely on .NET to get you there. Code sharing is as easy as possible because we provide a unified BCL.

Hope this is of any help. Please let me know anything new in this respect.

**Comment by axunonb** [comment]
Hi @Eitilt, could you solve the issue with UWP? Anything you'd like to share?

**Comment by Eitilt** [comment]
Sorry! I thought I had already responded. Unfortunately, I haven't gotten any farther in making it work – even trying to load it on a new, empty UWP project with all the defaults left unchanged, it still gives me those same errors, so it's probably not something in my own code causing the issue (though there is a chance it's Visual Studio; I haven't checked in the console). And like you say, it _should_ all be working just fine, and other libraries even do, it's just this one being strange. Best guess I have is that there's some packaging bug that's keeping it from loading and the package manager just _thinks_ it's due to a version mismatch, but at the same time that seems rather far-fetched.

**Comment by axunonb** [comment]
Hm, could you try to install [MailKit](https://www.nuget.org/packages/MailKit/)? If it works, this would give me hint regarding UWP.
