### ISSUE TITLE
ConditionalFormatter

### ISSUE THREAD

**Issue by veryevilzed** [scottrippey/SmartFormat.NET#98]
```
var addrList = new[] { new { Name = "Jim", Age = 32, Address = new { City = "New York", State = "NY" } } };
var result = Smart.Format("{Age:cond:>=55?Senior Citizen|>=30?Adult|>=18?Young Adult|>12?Teenager|>2?Child|Baby}", addrList);
```
Need: Adult
Result: Baby

**Comment by axunonb** [comment]
After a quick test with the latest version (2.1.0.2) the result is "Adult" as expected. Please double-check you're using this version.

**Comment by veryevilzed** [comment]
No, I try 2.1.0.2
I switch to .net 3.5, and run in Unity3d. 
Maybe problem here.
Ok, don't worry. I'm fork & fix.
