### ISSUE TITLE
Possibility to keep not Found selectors?

### ISSUE THREAD

**Issue by jogibear9988** [scottrippey/SmartFormat.NET#99]
Is to Possible to keep a Selector in the String if it is not found in the Object?

**Comment by axunonb** [comment]
Yes, this is possible with ```SmartSettings``` [as described in the Wiki](https://github.com/scottrippey/SmartFormat.NET/wiki/SmartSettings). You can e.g. choose to igrnore, to throw an exception etc. The corresponding Parser and Formatter properties are self-descriptive. Examples (you'll need the first one):
```Smart.Default.Settings.ParseErrorAction = ErrorAction.MaintainTokens;```
```Smart.Default.Settings.FormatErrorAction = ErrorAction.MaintainTokens;```

**Comment by jogibear9988** [comment]
Are also instance specific settings (not static ones) possible?

**Comment by axunonb** [comment]
Yes, it is like it is mentioned in the  [Wiki](https://github.com/scottrippey/SmartFormat.NET/wiki/SmartSettings):
> SmartSettings have the scope for each SmartFormatter instance (meaning they are not static).

```Smart.Format(...)``` are static methods of a static class. So you'll have to create an instance of ```SmartFormatter```. In this case remember to add required ```SourceExtensions``` and ```FormatterExtensions```, because they are not set by default.
